Create Observing_Anyons_2020
virtualscienceforum/virtualscienceforum pull request #142
Opened 2020-09-04 23:33 UTC by vfatemi

Webpage for the Observing Anyons 2020 mini-conference.

2020-09-04 23:41 UTC, vfatemi commented
- [ ] Confirm date and times of conference
- [ ] Add affiliation and link webpages of panelists
- [ ] Title, abstract, author list for each talk
- [ ] Schedule Zoom event
- [ ] Embed Zoom registration

2020-09-11 20:59 UTC, vfatemi commented
Temporarily added paper titles and paper links in lieu of actual seminar information.

2020-09-11 22:50 UTC, babaks77 commented on Observing_Anyons_2020
> +This year two experiments efforts claimed the first observation of fractional statistics in fractional quantum Hall devices.
experimental efforts ...

2020-09-11 22:58 UTC, babaks77 commented
I think the webpage looks good to start advertising.

2020-09-12 13:05 UTC, vfatemi commented
Fixed some words.

2020-09-12 13:09 UTC, akhmerov commented
> I think the webpage looks good to start advertising.

We should probably merge this first :P 

Let me know when it's time to review and merge.

2020-09-12 13:10 UTC, akhmerov requested changes
We need to link the event from the header and the table of contents

2020-09-12 13:32 UTC, akhmerov commented on _sidebar.md
> +    * [Observing_Anyons_2020](Observing_Anyons_2020.md)
```suggestion
    * [Observing Anyons 2020](Observing_Anyons_2020.md)
```

2020-09-12 13:33 UTC, vfatemi commented
> We need to link the event from the header and the table of contents

Did these just now, but I have to depart for a bit. I haven't yet sorted out the "test changes to the markdown content locally" mechanism.

2020-09-12 22:52 UTC, merged