Replace special chars in title
virtualscienceforum/virtualscienceforum pull request #366
Opened 2021-05-03 20:54 UTC by everthemore

Interpratation of how markdown does it [here](https://github.com/gjtorikian/html-pipeline/blob/main/lib/html/pipeline/toc_filter.rb), by 

1. Converting to lower
2. Removing all punctuation except for '-'
3. Replace whitespace with '-'

I don't check for uniqueness, since two identical titles is going to be extremely rare

2021-05-03 21:44 UTC, akhmerov commented
This is amazing, I don't actually understand how it works! Something to learn. I only have one remark: please also apply the filter to the speakers' corner template.

2021-05-03 21:54 UTC, akhmerov commented
OK, I now understand how it works, and it's still cool!

2021-05-04 07:18 UTC, everthemore commented
Thanks! :) 
See here for a timing of string.translate vs regex replacements (which I tried originally): https://stackoverflow.com/questions/265960/best-way-to-strip-punctuation-from-a-string

2021-05-04 08:56 UTC, akhmerov requested changes

2021-05-04 08:56 UTC, akhmerov commented on templates/speakers_corner.md.j2
> +> **Authors:** {{ talk.authors }}
```suggestion
> **Authors:** {{ talk.authors }}  
```

2021-05-04 08:56 UTC, akhmerov commented on templates/speakers_corner.md.j2
> +Authors: {{ talk.authors }}
```suggestion
Authors: {{ talk.authors }}  
```

2021-05-04 08:59 UTC, merged

2021-05-04 09:02 UTC, everthemore commented
Thanks for fixing those, still not quite sure why Atom decides to replace some but not all